// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ4svohnOUXvwyLu9rpb4MzzTWqQnhXY0',
    appId: '1:931158256122:web:7f35a63ad7a48752419c43',
    messagingSenderId: '931158256122',
    projectId: 'superconversionhero',
    authDomain: 'superconversionhero.firebaseapp.com',
    storageBucket: 'superconversionhero.appspot.com',
    measurementId: 'G-YNDB407FE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgNtoc-3TQ3fyBQWB7Vy1Vd8_TWp4moL8',
    appId: '1:931158256122:android:4389e11efb9e7324419c43',
    messagingSenderId: '931158256122',
    projectId: 'superconversionhero',
    storageBucket: 'superconversionhero.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACKlHwNsUecFHnDGHk_8OPf-uT1nedqKA',
    appId: '1:931158256122:ios:b6d5509c6ba5890a419c43',
    messagingSenderId: '931158256122',
    projectId: 'superconversionhero',
    storageBucket: 'superconversionhero.appspot.com',
    iosClientId: '931158256122-q1cnbr4sb9n4iiqngvkgoo9cp7buo28e.apps.googleusercontent.com',
    iosBundleId: 'com.conversionista.superconversionhero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACKlHwNsUecFHnDGHk_8OPf-uT1nedqKA',
    appId: '1:931158256122:ios:b6d5509c6ba5890a419c43',
    messagingSenderId: '931158256122',
    projectId: 'superconversionhero',
    storageBucket: 'superconversionhero.appspot.com',
    iosClientId: '931158256122-q1cnbr4sb9n4iiqngvkgoo9cp7buo28e.apps.googleusercontent.com',
    iosBundleId: 'com.conversionista.superconversionhero',
  );
}
